### ISSUE TITLE
menu should close if right click again somewhere else

### ISSUE THREAD

**Issue by yeban** [sydcanem/bootstrap-contextmenu#72]
Right click to open bootstrap contextmenu. Then right click somewhere else to open browser's default contextmenu.

Here's what we get:
![screen shot 2014-11-25 at 3 06 00 pm](https://cloud.githubusercontent.com/assets/90373/5180695/a72974ba-74b4-11e4-9806-b3910a33c8d8.png)

Expected: only browsers right click menu should be visible

**Comment by rgriffith** [comment]
I am experiencing this same issue with v0.3.2. I tried adding `data-toggle="context"` to my elements, but that does not work. Here is how I am using the plugin:

```
$('#page-container').contextmenu({
    target: '#context-menu',
    scopes: '.context',
    before: function(e, ctx) {
      console.log("Menu is about to open.");
      return true;
    }
  });
```

Any suggestions would be greatly appreciated. Thanks!

**Comment by yeban** [comment]
I can only ask you to make sure that `data-toggle-"context"` is applied to `#page-container` element. I'm also wondering, from the name of it, how big is this 'page-container' are subsequent right clicks being triggered outside the container?

**Comment by rgriffith** [comment]
The `#page-container` element is the outermost container on my page and spans the entire width and height. Adding `data-toggle="context"` to `#page-container` will work since it essentially replaces all context menus; however, it does not produce the desired effect. What I would like to do is only replace the context menu for specific links within my page (`.cs-context` and `.link-with-context`), leaving the default browser context menu everywhere else.
